url: http://villavarsovia.com
baseurl:

# Site settings
title: Villa Varsovia - Esterillos, Costa Rica
email: your-email@domain.com
description: "Alone on a breezy hill, this vacation rental is a secluded oasis. Fruit trees grow in the garden; playful monkeys are regular visitors; curious iguanas live on the grounds; and macaws fly above in pairs, squawking like an old married couple."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e74c3c
  secondary: e74c3c
  secondary-dark: 000000

# Team names, titles and social links
people:
- name: Marta Wieladek
  pic: marta.jpg
  social:



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/VillaVarsovia
    color: 3b5998


# Postal address (add as many lines as necessary)
address:
  - line: Villas Xhu
  - line: Esterillos, Puntarenas, Costa Rica

# Build settings
markdown: kramdown
permalink: pretty