url: http://villavarsovia.github.io
baseurl: /website/

# Site settings
title: Villa Varsovia
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e74c3c
  secondary: e74c3c
  secondary-dark: 000000

# Team names, titles and social links
people:
- name: Marta Wieladek
  pic: marta.jpg
  social:
    - title: pinterest
      url: http://www.pinterest.com/mwieladek/
    - title: facebook
      url: https://www.facebook.com/marta.wieladek


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/VillaVarsovia


# Postal address (add as many lines as necessary)
address:
  - line: Villas Xhu
  - line: Esterillos, Puntarenas, Costa Rica

# Build settings
markdown: kramdown
permalink: pretty